// makes npc move random direction while alive
// called in mob/NPC/Resting()
mob/NPC/proc/step_rand_loop()
	while(src && !combat_flag.dead)
		var/_locToWalk
		dir = pick( NORTH, SOUTH, EAST, WEST)
		switch(dir)
			if(NORTH)
				_locToWalk = locate(x,y+2,z)
			if(SOUTH)
				_locToWalk = locate(x,y-2,z)
			if(EAST)
				_locToWalk = locate(x+2,y,z)
			if(WEST)
				_locToWalk = locate(x-2,y,z)
		walk_towards(src, _locToWalk,2,1)
		sleep(rand(50,110))
