
#define CLOTHING_LAYER	MOB_LAYER+1
#define HAIR_LAYER		MOB_LAYER+2
#define SWORD_LAYER		MOB_LAYER+3
#define RELEASE_LAYER	MOB_LAYER+4
#define AURA_LAYER		MOB_LAYER+5
#define AURA_EFFECT_LAYER MOB_LAYER+5