#define TRAINING_DELAY 10
#define LEVELUP_HEALTH_BONUS 70
#define LEVELUP_REIATSU_BONUS 30
#define LEVELUP_ATTACK_BONUS 2
#define LEVELUP_REISHI_BONUS 2
#define LEVELUP_HIERRO_BONUS 2

#define SYS_LEVELING_BONUS
//#define SYS_LEVELING_POINTS
#define SYS_LEVELING_POINTS_OVERRULE

#define SYS_LEVELING_POINTS_MULTIPLVAL 11.5
#define SYS_LEVELING_AWARED_STAT_POINTS 1 //overruled