
// Spawn locations
#define SPAWN_LOC_HUMAN 11,24,3
#define SPAWN_LOC_SOUL
#define SPAWN_LOC_HOLLOW
#define SPAWN_LOC_ARRANCAR
#define SPAWN_LOC_QUINCY
#define SPAWN_LOC_SHINIGAMI
#define SPAWN_LOC_VAIZARD

#define NEW_PLAYER_LOC 33,26,1