#define MOB_STEP_SIZE 4
#define MONSTER_STEP_SIZE 2
#define OBJ_STEP_SIZE 2


#define SPELL_BALA_STEP_SIZE	TILE_WIDTH * 0.6
#define SPELL_CERO_STEP_SIZE	TILE_WIDTH * 0.2
#define SPELL_GRC_STEP_SIZE		TILE_WIDTH * 0.5