
#define	Bold(t)		"<b>[t]</b>"
#define	Italic(t) 	"<i>[t]</i>"
#define	Underline(t) "<u>[t]</u>"
#define	Red(t)		"<font color=#ff0000>[t]</font>"
#define Orange(t)	"<font color=#ffA500>[t]</font>"
#define	Green(t)	"<font color=#00ff00>[t]</font>"
#define	Blue(t)		"<font color=#0000ff>[t]</font>"
#define	Cyan(t) 	"<font color=#00ffff>[t]</font>"
#define	Turquoise(t) "<font color=#00ced1>[t]</font>"
#define	Grey(t) 	"<font color=#d3d3d3>[t]</font>"
#define	Silver(t) 	"<font color=#c0c0c0>[t]</font>"
#define	Yellow(t) 	"<font color=#ffff33>[t]</font>"
#define	Gold(t) 	"<font color=#e3ae01>[t]</font>"

#define Melee(t)	"<font color=#e3ae01>[t]</font>"
#define Bleed(t)	"<font color=#Bf0000>[t]</font>"
#define Burn(t)		"<font color=#ffA500>[t]</font>"
#define Toxin(t)	"<font color=#009200>[t]</font>"
#define Freeze(t)	"<font color=#81d4fa>[t]</font>"
